// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzStVYUZ3frvzGdMiw1V6vbmOTjCKwkwQ',
    appId: '1:778720037769:web:e0f472c1abe3c25f972f58',
    messagingSenderId: '778720037769',
    projectId: 'instagram-clone-cours-eyecode',
    authDomain: 'instagram-clone-cours-eyecode.firebaseapp.com',
    storageBucket: 'instagram-clone-cours-eyecode.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-YwgUCwNft9GfIEbvdzquPpb78kbY5I',
    appId: '1:778720037769:android:a8ad8367bb940dd0972f58',
    messagingSenderId: '778720037769',
    projectId: 'instagram-clone-cours-eyecode',
    storageBucket: 'instagram-clone-cours-eyecode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqI-Ja3o1o9wZhNDAyrA7ooZgZY0cELHg',
    appId: '1:778720037769:ios:d6197611d3e6afb4972f58',
    messagingSenderId: '778720037769',
    projectId: 'instagram-clone-cours-eyecode',
    storageBucket: 'instagram-clone-cours-eyecode.appspot.com',
    iosClientId: '778720037769-b5dv8feuh488c4c3pe2rsrj900fif65h.apps.googleusercontent.com',
    iosBundleId: 'se.eyecode.instagramCloneCourse',
  );
}
